### ISSUE TITLE
Update for nopCommerce 4.60

### ISSUE THREAD

**Issue by jamie-burns** [Bungalow64/NOP-Plugin-ScheduleTaskLog#5]

**Comment by Bungalow64** [comment]
The updated plugin has been submitted for review.  Once it has been approved for the nopCommerce marketplace this issue will be closed.

**Comment by Bungalow64** [comment]
The plugin is now on the marketplace: https://www.nopcommerce.com/en/enhanced-schedule-task-monitoring
